name: CI

on:
  push:
    branches: [ main, release* ]
  pull_request:
    branches: [ main, release* ]

jobs:
  build-and-test:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for GitVersion

      - name: Calculate Version
        id: calculate_version
        uses: ./.github/actions/calculate-version

      - name: Dispaly Updated Project File
        run: cat SaturdayMP.NConstraints/SaturdayMP.NConstraints.csproj

      - name: Run Tests
        run: dotnet test

      - name: Create NuGet Package
        run: dotnet pack --configuration Release --output SaturdayMP.NConstraints/bin/Release

      - name: Upload NuGet Package to Action
        uses: actions/upload-artifact@v3
        with:
          name: SaturdayMP.NConstraints.${{ env.nugetversionv2 }}.nupkg
          path: SaturdayMP.NConstraints/bin/Release/SaturdayMP.NConstraints.${{ env.nugetversionv2 }}.nupkg
          if-no-files-found: error

      - name: Upload to MyGet
        run: dotnet nuget push SaturdayMP.NConstraints/bin/Release/SaturdayMP.NConstraints.${{ env.nugetversionv2 }}.nupkg --source https://www.myget.org/F/saturdaymp/api/v3/index.json --api-key ${{ secrets.MYGET_API_KEY }}

      