name: CI

on:
  push:
    branches: [ main, release* ]
    tags: [ v* ]
  pull_requests:
    branches: [ main, release* ]

jobs:
  build-and-test:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for GitVersion

      - name: Calculate Version
        id: calculate_version
        uses: ./.github/actions/calculate-version

      - name: Dispaly Updated Project File
        run: cat SaturdayMP.NContraints/SaturdayMP.NConstraints.csproj

      - name: Run Tests
        run: dotnet test
      